kind: ENC[AES256_GCM,data:27kC1PAv,iv:JUyuERgBq10tnvJRuTnBuFTWD8hpfbxPZdnwDVx5Gak=,tag:gOeGnEhz8XosCf4Xv52vVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:R26vbckZgAZwrg==,iv:3kX7lwMa284cynzST54gCW7LWXhJVCzGwEdXTk7XXe8=,tag:I1JEA38uiL5ouVEloT9TnA==,type:str]
stringData:
    key: ENC[AES256_GCM,data:YQvTv3oCx09WjlkIR24tbRWo47YmnYgAic5sQtTGe5RZ5QKOq4r38HPyCl8VJ3SLlqSVGh43ROAkdWpdJIx2P+QGTsxf7/VeZRVSAQRGZKQsIP6BIB37MxXcTFfmprsH9Okkp5qFYzFUffRyjF5nvrUGUWJZghUI8KzdhEdwjNFFjr6SAFfyy9N/p/3W23225JlGxMRAN0YJJoNBsecbDv9JmJC/WjijUTyfs9o5trc2EP1PFtYAQC4crUDqi91EVDMlInVE/BX0J+zm+cXlVanSwTcBbhLyud/HdE2+QsT2uI5kt0NJOEASptaeQZvHf5uhWDrdwZNOhpJ/tzqPGZj9VPAb9KKU9dJse7K317Lx5Tz51ckmOoyb21U9EJgZZiYDuJkrewKPfz+sAuliyCcoqGSA+3eOTvi/3CN3trsm08oTWllmJF7ZNbIcReev00A5OYawBHjFxsgsh61ZmtXok5bRuig=,iv:5vngbZvPzdKiS92MlkkzAp4xhZMz8kJ/agW/vShDCh4=,tag:irANYUaMMJWgpheAfid5jw==,type:str]
sops:
    age:
        - recipient: age1h7y2etdv5r0nclaaavral84gcdd2kvvcu2h8yes3e3k3fcp03fzq306yas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWGN5Yk8xQytqUVJtRDlx
            SmU3OXNBRzZJNmNEVEJkckNmM3BHMUYyd2lvCmNINi84ZG0zOUNVR2FrSUhoRXJE
            YWdsOGtnTjhjc2l6TkxhSXNiZmhIZ0EKLS0tIFR4bXpkN0l5TEFRT3Vpci9XV0Zk
            bDdIZGdkbGVkSzBuajc3alEwUCtqTTAKgcCkxwOfqJas4DRZzVv9sS10/Fk0IY7f
            cTCHP90lBFUKhBKiE4eowt53FzVtlKdgW88ycG/yJoWDiKDJVZ+GHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T10:29:05Z"
    mac: ENC[AES256_GCM,data:QY+eeGsLE0pbBMYYa5yU//8mR/a+jlOYlGtH3oiaSfJRd6P+N6Mdo9uOxf9hqKNEm3J82/qI87SjtVSZAzU/wep7XpCO2x8B397ZPQnsMywxc7YqSYyO9AvF231xGejF4XU4C+Qm18VqrbBiaE8dZIWq3usoeKKdPoW3vP7pmNE=,iv:pL8oYpR27FSBbA8Tlr6D5Jj38ioMgB1TB/10ZTGn34A=,tag:2elYcuisexvg6VThPJHYsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
