kind: ENC[AES256_GCM,data:NdNTd7H5,iv:YPLQ4mbtwHs+NJeKxrMAhmmOkdaNAIxMHE5cM35P8bE=,tag:P6b2SFPrz1X1uPDl329fJQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:awusfCEGodoc1Q==,iv:Tsl52ILW8GPx0akFwb5UQDarJy8V8a0udtpWa8R6l9w=,tag:3lG6yN5QdZGg2Sa8ddcP9g==,type:str]
stringData:
    key: ENC[AES256_GCM,data:2ktigyT0BxkjA4HIfEPCssD9a4VdA2/niq3RAGbjIfYPz4thMA88LdQY9qK5AdUS7+5rhe2L6kkI9n7k3BoBz014do6aH8ipOpAHAaIgYX0G7Hqo/YbGjI5KHoLPPzN2Z8rvYFT7jz5BW4CkSXIG3SgKDmA2PNI6ha5GRHUQZdRr+Ep/OXPuTwmT5AL/uz2bIUWox3h13YNSffMjFqwM0KI7nQhW0CrbtkHe6bmyynyS4UOQaUihiGAswitvS/U94gbp4pmMLfJ/ZbLpJCLkzjNDoMSKKF/mnwheZalvHXtb8EPzBc25H9aayhHkq1CWQQX8OBx9wGE4qLUaVNyKKzFh6/zMYi3HOAeDZqxNPHtFDPyEKQ+vqvNJtzArqcX1M++pRiEySXczmbnSEjGlImYU4BlZfOVAOiIt0HVuqzeC4EUAi7shtoxd1vksyBSF3RYJZPKiDij57T98uuAQwBQ3rX6qal0=,iv:GOG9svyoaBvxvEe03pcdcBBJLxHzwfqj8OrLykU8eGQ=,tag:3AboDL0NiKA7TIIkvp9Gtw==,type:str]
sops:
    age:
        - recipient: age1h7y2etdv5r0nclaaavral84gcdd2kvvcu2h8yes3e3k3fcp03fzq306yas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMS29yNDNxWDExRHM4Z3J6
            RWRRdUtHWjNsSTAyVFBpdERNWFFPa0xaN2lJCjg3OVRjSVRrUVdLbE4wMk9qeXhu
            amxUZDd5ajNRL2oxUy9jcGwxUUVTZmsKLS0tIGwyQzhWYWQ5SnlkdklCQy9tekNR
            S3d0UXE2a2JHa0pFREJTelhpT3h4L0EKnrTRJQVt4bMnaX+VGMpBZP4gEw681QYy
            eNeL7dXoT5pAcw158PVW7I2jNvkdkSr272B4MIqO10bQtY25sUZVNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T09:14:05Z"
    mac: ENC[AES256_GCM,data:JSCGg/QaO1Hi4RLlJs4JLWqsZA0N5PxcG/nD2bVqRVYBwjL7o5MwRUYiurzCYfdrgI1UdGy+sSYC4eAsTqKsxSrPSZ1274XIBgSw+C/++aS8wy+FJf8QQI5hkybVD3pikTK2ELuUr3iJ4Yj48rPjknZbQyUxgUAHXgDUBp5v+b8=,iv:xdoG9BXdNPuNKGYiX3IURh8iA/l9Dj5C4oOwlXmyGzQ=,tag:xnmWyiEDoGv7WQCXoi4ELA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
