kind: ENC[AES256_GCM,data:EVbvC3OM,iv:Qm4/srlcqiWwtN5Klt0j8zliNN2lFul2xsXEPCKpDXA=,tag:OEIWDZYYn3eprhR/4LiR+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xDfPrPUrHYchzA==,iv:nBpVFOwK/yykPHkWwmy8LX54EN5xzGzOwyFZ7Udboxg=,tag:MlI2E29DnP04lZIKEJIc0A==,type:str]
stringData:
    key: ENC[AES256_GCM,data:Hx9Ffipi8mgXnQDEzM6LidNfHZRee/AOTc4zn8B6WkQCxHLQZWlP1eWfmiskzmqC9iAG0+uuCWoQwA98oWKFDUH5Ersd3UwZxlemepq/N3ko/60owqrYsSB2MgDJ3zrRLDhrDZOZaAfnMyzfy+p+ALVNEy01hrm5cyE/yvgK6YSFBRoom0hFEsfhfut0k15KviJOEmA7qPaUwYxvK6ZpPv4ft/efj7PJpv2PsdosmdecGa58qfBwcsrcr9CAlUc0TBfk64P4/e7DFbQWAAQRbQMAn+TfogoNdgD3VzBQsdv6KjtU3cn+vAEjdf9x3+8e85dbDRWqYQPXbM5F/JHfyWfBQZYn5QPDzyV8mKdG90+29CbUPcdM0eZXu2WiE7ESxEVgwg6ilmGUYzRwBiOfqxqPeaAddvmK0DAVvKExuBujBMcIFLOcq9z92p3LcEtLCuiYZSGb5sKlqH6Me4fpDa+9IFRoXUs=,iv:iptu0R0ORYz4fh4tU/M0tqfkOMTyN6BRMj2KA3iRkeo=,tag:vYhDpwp/tECTL4pPdSlCqw==,type:str]
sops:
    age:
        - recipient: age1h7y2etdv5r0nclaaavral84gcdd2kvvcu2h8yes3e3k3fcp03fzq306yas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVlBHcmhhSFlJcDd2NmZL
            cnI0cHNIMzlORGtrNW0wVlIxcFEyM0JxSjIwClZ6NW94am1aRzB0VVRqVGZocy8x
            d3dOdGQyWHVNaGJuZVNXVEN4cEEvQW8KLS0tIFFCcGEwaVB2cjU4THJQdktuZXZ5
            aEFsbGJudWlFUS9Mck1RYU83UTAwYWsKl7cwofsLHY0ijXQlLYhU1WkiHWw0RDMb
            uEkwxk9tX2hoYPz7ZzOm0DjKIJkeijViwzLiLLC/clE+yJF7PEYFQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T15:26:49Z"
    mac: ENC[AES256_GCM,data:xJm1yOfFkHVkdlAxoARds5dF+wUUo3X6DVhzB7bvh48+dv8ALCAM+bd0uekepWGN1n3982WJZL6Hhrc2sC0Fsg3udwPtQKdOLJXG0PLo7ja+W9GsQ+6sPiJGcMA8n43Jzo34WWO5iVstCl6Z3GFxzk24mI7HtWHmCiGu70W4vZ0=,iv:6jZpWncmkVhlb/ZwO6Dv9SIWq6UvwmnemnUrEvyc7iY=,tag:MlHuuPC56RhXca4/Q/3JRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
