kind: Secret
metadata:
  name: git-work-config
stringData:
  config: REPLACE_WITH_WORK_GITCONFIG_CONTENT_2025-11-19T08:18:28Z
sops:
  version: 3.8.0
  age:
    - recipient: age1h7y2etdv5r0nclaaavral84gcdd2kvvcu2h8yes3e3k3fcp03fzq306yas
      enc: ENC[AES256_GCM,data:placeholder,iv:placeholder,tag:placeholder,type:str]
