kind: Secret
metadata:
  name: git-work.gitconfig
stringData:
  key: |
    age-encryption.org/v1
    -> X25519 ox5mBP6oCqYcgrY4CTdmSOGMpsVFknCox8B/bnYQKFg
    eUtuHTrUK5zf7EljdaeHcyQ9f9il+1X0QOhdKCEwoZw
    --- 91uHmAC4inwxqxVewpPj4zfcnfQygDKcXjMqLCdsWG0
