apiVersion: v1
kind: Secret
metadata:
  name: aws-config
stringData:
  config: |-
    [default]
    region=us-east-1
    output=json
sops:
  mac: ENC[AES256_GCM,data:placeholder,iv:placeholder,tag:placeholder,type:str]
  version: 3.8.0
  encrypted_regex: '^(config)$'
  age:
    - recipient: age1h7y2etdv5r0nclaaavral84gcdd2kvvcu2h8yes3e3k3fcp03fzq306yas
      enc: ENC[AES256_GCM,data:placeholder,iv:placeholder,tag:placeholder,type:str]
